name: Bug in Entity Framework Core
description: Create a report about something that isn't working
labels: ["customer-reported"]
body:
  - type: markdown
    attributes:
      value: Test
  - type: textarea
    id: code
    attributes:
      label: Your code
      description: |-
        To fix any bug we must first reproduce it. To make this possible, please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing.

        It is often impossible for us to reproduce a bug when working with only code snippets since we have to guess at the missing code. 
      render: csharp
    validations:
      required: true
  - type: textarea
    id: stack
    attributes:
      label: Stack traces
      description: |-
        Include the full exception message and stack trace for any exception you encounter. 
      render: text
    validations:
      required: false
  - type: textarea
    id: output
    attributes:
      label: Verbose output
      description: |-
        Include `--verbose` output when filing bugs about the `dotnet ef` or Package Manager Console tools.
      render: text
    validations:
      required: false
